image:
  file: .gitpod.Dockerfile

ports:
    - port: 3000
      onOpen: open-preview
    - port: 27017
      onOpen: notify
    - port: 28017
      onOpen: open-browser
tasks:
  - init: pip3 install -r requirements.txt